trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  WORKDIR: '$(System.DefaultWorkingDirectory)'  # change if tests are in a subfolder

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node.js 20'

- script: npm ci
  workingDirectory: '$(WORKDIR)'
  displayName: 'Install npm dependencies'

- script: npx playwright install --with-deps
  workingDirectory: '$(WORKDIR)'
  displayName: 'Install Playwright browsers & deps'

- script: npx playwright test --reporter=junit
  workingDirectory: '$(WORKDIR)'
  displayName: 'Run Playwright Tests'
  env:
    CI: 'true'
    PLAYWRIGHT_BROWSERS_PATH: '0'

- task: PublishTestResults@2
  displayName: 'Publish Playwright Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    # Playwright's JUnit file name can vary; cover common names:
    testResultsFiles: |
      **/junit*.xml
      **/results.xml
    searchFolder: '$(WORKDIR)'
    mergeTestResults: true
