import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://admin.sqzvip.com/auth/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('legalsqueez@yopmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Welcome@1');
  await page.getByRole('checkbox', { name: 'I Accept theTerms & Conditions' }).check();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: '  Category' }).click();
  await page.locator('div').filter({ hasText: /^RestaurantsAdd Restaurants information$/ }).nth(3).click();
  await page.getByRole('button', { name: ' Add Restaurant' }).click();
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').fill('Bihari restaurant');
  await page.locator('input[name="name"]').press('Tab');
  await page.getByPlaceholder('1 (702) 123-').fill('+1 874-563-25895');
  await page.locator('.ql-editor').first().click();
  await page.locator('.ql-editor').first().fill('great');
  await page.getByPlaceholder('Latitude').click();
  await page.getByPlaceholder('Latitude').fill('1.23');
  await page.getByPlaceholder('Longitude').click();
  await page.getByPlaceholder('Longitude').fill('2.36');
  await page.locator('.css-19bb58m').first().click();
  await page.getByText('America/Denver').click();
  await page.locator('input[name="addressName"]').click();
  await page.locator('input[name="addressName"]').fill('100');
  await page.getByPlaceholder('Street').click();
  await page.getByPlaceholder('Street').fill('200');
  await page.locator('.pt-3 > .css-b62m3t-container > .css-15noair-control > .css-hlgwow > .css-19bb58m').first().click();
  await page.locator('#react-select-3-input').fill('ind');
  await page.getByText('India (IN)').click();
  await page.locator('.pt-3 > .css-b62m3t-container > .css-15noair-control > .css-hlgwow > .css-19bb58m').first().click();
  await page.locator('#react-select-4-input').fill('bih');
  await page.getByText('Bihar', { exact: true }).click();
  await page.getByText('City *Select City').click();
  await page.locator('#react-select-5-input').fill('pat');
  await page.getByText('Patna', { exact: true }).click();
  await page.getByPlaceholder('Zip').click();
  await page.getByPlaceholder('Zip').fill('965874');
  await page.getByPlaceholder('Booking URL').click();
  await page.getByPlaceholder('Booking URL').fill('htpps.com');
  await page.getByPlaceholder('Email', { exact: true }).click();
  await page.getByPlaceholder('Email', { exact: true }).fill('abvf@gmail,com');
  await page.getByPlaceholder('Type', { exact: true }).click();
  await page.getByPlaceholder('Type', { exact: true }).fill('india');
  await page.getByPlaceholder('Email', { exact: true }).click();
  await page.getByPlaceholder('Email', { exact: true }).fill('abvf@gmail.com');
  await page.getByPlaceholder(' Restaurant Menu URL').click();
  await page.getByPlaceholder(' Restaurant Menu URL').fill('menu');
  await page.getByPlaceholder('Convenience Fee').click();
  await page.getByPlaceholder('Convenience Fee').fill('010');
  await page.getByPlaceholder('Minimum Threshold Amount').click();
  await page.getByPlaceholder('Minimum Threshold Amount').fill('12');
  await page.getByPlaceholder('Auto - Approved Amount (per').click();
  await page.getByPlaceholder('Auto - Approved Amount (per').fill('72');
  await page.getByPlaceholder('Please enter the person count').click();
  await page.getByPlaceholder('Please enter the person count').fill('4');
  await page.getByPlaceholder('Please enter the maximum price').click();
  await page.getByPlaceholder('Please enter the maximum price').fill('72');
  await page.getByPlaceholder('Domain URL').click();
  await page.getByPlaceholder('Domain URL').fill('uipo');
  await page.getByText('Submit').click();
});